name: $(BuildID)

parameters:
  - name: deployFromFeature
    displayName: "Deploy from Feature Branch"
    type: boolean
    default: false


trigger:
  batch: true
  branches:
    include:
      - "*"
  paths:
    include: 
      - infra-shared/*

pr:
  branches:
    include:
      - main
  paths:
    include:
      - infra-shared/*

resources:
  repositories:
    - repository: PipelineCommon
      name: DEFRA-DEVOPS-COMMON/Defra.Pipeline.Common
      type: git

extends:
  template: /templates/pipelines/common-infrastructure-deploy.yaml@PipelineCommon
  parameters:
    projectName: trade-exportscore-trp
    deployFromFeature: ${{ parameters.deployFromFeature }}
    privateAgentName: "DEFRA-COMMON-ubuntu2004-SSV3"
    variableFiles:
      - /vars/common.yaml@self
      - /vars/{environment}.yaml@self
    regionalVariableFiles:
      - /vars/regional/{environment}-{region}.yaml@self
    groupedTemplates:
      - name: TRP
        templates:
          - name: log-analytics-workspace
            path: infra-shared/operational-insights
            type: bicep
            scope: 'Resource Group'
            resourceGroupName: '$(environment)$(project)$(nc-function-infrastructure)$(nc-resource-resourcegroup)$(subscriptionNumber)$(regionNumber)08'
          - name: service-bus
            path: infra-shared/service-bus
            type: bicep
            scope: 'Resource Group'
            resourceGroupName: '$(environment)$(project)$(nc-function-infrastructure)$(nc-resource-resourcegroup)$(subscriptionNumber)$(regionNumber)08'
            postDeployScriptsList:
              - displayName: Resolve Private Endpoint IP for Service Bus
                scriptRepo: PipelineCommonScripts
                scriptPath: "Get-ResourcePrivateEndPointsDnsRecordsAsJson.ps1@PipelineCommon"
                ScriptArguments: >
                  -ResourceGroupName '$(environment)$(project)$(nc-function-infrastructure)$(nc-resource-resourcegroup)$(subscriptionNumber)$(regionNumber)08'
                  -ResourceName '$(environment)$(project)$(nc-function-infrastructure)$(nc_servicebus)$(subscriptionNumber)$(regionNumber)08'
              - displayName: Set DNS record for Service Bus
                scriptPath: "Set-PrivateDnsRecordSet.ps1@PipelineCommon"
                scriptRepo: PipelineCommonScripts
                serviceConnectionVariableName: msServiceConnectionName
                ScriptArguments: >
                  -Ttl 120
                  -UpdateAllDnsZones 1
          - name: key-vault
            path: infra-shared/key-vault
            type: bicep
            scope: 'Resource Group'
            postDeployScriptsList:
              - displayName: Resolve Private Endpoint IP for Key Vault
                scriptPath: "Get-ResourcePrivateEndPointsDnsRecordsAsJson.ps1@PipelineCommon"
                ScriptArguments: >
                  -ResourceGroupName '$(environment)$(project)$(nc-function-infrastructure)$(nc-resource-resourcegroup)$(subscriptionNumber)$(regionNumber)08'
                  -ResourceName '$(environment)$(project)$(nc-function-infrastructure)$(nc_keyvault)$(subscriptionNumber)$(regionNumber)08'
              - displayName: Set DNS record for Key Vault
                scriptPath: "Set-PrivateDnsRecordSet.ps1@PipelineCommon"
                serviceConnectionVariableName: msServiceConnectionName
                ScriptArguments: >
                  -Ttl 120
                  -UpdateAllDnsZones 1
            resourceGroupName: '$(environment)$(project)$(nc-function-infrastructure)$(nc-resource-resourcegroup)$(subscriptionNumber)$(regionNumber)08'
          - name: container-registry
            path: infra-shared/container-registry
            type: bicep
            scope: 'Resource Group'
            resourceGroupName: '$(environment)$(project)$(nc-function-infrastructure)$(nc-resource-resourcegroup)$(subscriptionNumber)$(regionNumber)08'
            postDeployScriptsList:
              - displayName: Resolve Private Endpoint IP for Container Registry
                scriptRepo: PipelineCommonScripts
                scriptPath: "Get-ResourcePrivateEndPointsDnsRecordsAsJson.ps1@PipelineCommon"
                ScriptArguments: >
                  -ResourceGroupName '$(environment)$(project)$(nc-function-infrastructure)$(nc-resource-resourcegroup)$(subscriptionNumber)$(regionNumber)08'
                  -ResourceName '$(environment)$(project)$(nc-function-infrastructure)$(nc_containerregistry)$(subscriptionNumber)$(regionNumber)08'
              - displayName: Set DNS record for Container Registry
                scriptPath: "Set-PrivateDnsRecordSet.ps1@PipelineCommon"
                scriptRepo: PipelineCommonScripts
                serviceConnectionVariableName: msServiceConnectionName
                ScriptArguments: >
                  -Ttl 120
                  -UpdateAllDnsZones 1
          - name: managed-environment
            path: infra-shared/managed-environment
            type: bicep
            scope: 'Resource Group'
            resourceGroupName: '$(environment)$(project)$(nc-function-infrastructure)$(nc-resource-resourcegroup)$(subscriptionNumber)$(regionNumber)08'
          - name: postgresql
            path: infra-shared/postgresql
            type: bicep
            scope: 'Resource Group'
            resourceGroupName: '$(environment)$(project)$(nc-function-infrastructure)$(nc-resource-resourcegroup)$(subscriptionNumber)$(regionNumber)08'
          - name: application-insights
            path: infra-shared/application-insights
            type: bicep
            scope: 'Resource Group'
            resourceGroupName: '$(environment)$(project)$(nc-function-infrastructure)$(nc-resource-resourcegroup)$(subscriptionNumber)$(regionNumber)08'

    environments:
      - name: dev1
        serviceConnection: AZR-EXP-DEV1
        deploymentBranches:
          - "refs/heads/main"
        developmentEnvironment: true
        privateAgentName: "DEFRA-COMMON-ubuntu2004-SSV3"
        azureRegions:
          primary: "UKSouth"
      - name: snd1
        dependsOn: dev1
        serviceConnection: AZR-EXP-SND1
        deploymentBranches:
          - "refs/heads/main"
        privateAgentName: "DEFRA-COMMON-ubuntu2004-SSV3"
        azureRegions:
          primary: "UKSouth"
      - name: pre1
        dependsOn: snd1
        serviceConnection: AZR-EXP-PRE1
        deploymentBranches:
          - "refs/heads/main"
        privateAgentName: "DEFRA-COMMON-ubuntu2004-SSV5"
        azureRegions:
          primary: "UKSouth"
      - name: prd1
        dependsOn: pre1
        serviceConnection: AZR-EXP-PRD1
        deploymentBranches:
          - "refs/heads/main"
        privateAgentName: "DEFRA-COMMON-ubuntu2004-SSV5"
        azureRegions:
          primary: "UKSouth"
